export const GET_CHATROOM_REQUEST = "GET_CHATROOM_REQUEST";
export const GET_CHATROOM_SUCCESS = "GET_CHATROOM_SUCCESS";
export const GET_CHATROOM_FAIL = "GET_CHATROOM_FAIL";
export const GET_CHATROOM_RESET = "GET_CHATROOM_RESET";

export const LIST_MESSAGES_BY_CHATROOM_REQUEST =
  "LIST_MESSAGES_BY_CHATROOM_REQUEST";
export const LIST_MESSAGES_BY_CHATROOM_SUCCESS =
  "LIST_MESSAGES_BY_CHATROOM_SUCCESS";
export const LIST_MESSAGES_BY_CHATROOM_FAIL = "LIST_MESSAGES_BY_CHATROOM_FAIL";
export const LIST_MESSAGES_BY_CHATROOM_RESET =
  "LIST_MESSAGES_BY_CHATROOM_RESET";

export const ON_UPDATE_CHATROOM = "ON_UPDATE_CHATROOM";

export const ON_CREATE_MESSAGE = "ON_CREATE MESSAGE";

export const ON_CREATE_ATTACHMENT = "ON_CREATE_ATTACHMENT";

export const CREATE_CHATROOM_REQUEST = "CREATE_CHATROOM_REQUEST";
export const CREATE_CHATROOM_SUCCESS = "CREATE_CHATROOM_SUCCESS";
export const CREATE_CHATROOM_FAIL = "CREATE_CHATROOM_FAIL";
export const CREATE_CHATROOM_RESET = "CREATE_CHATROOM_RESET";

export const COMMON_CHATROOM_REQUEST = "COMMON_CHATROOM_REQUEST";
export const COMMON_CHATROOM_SUCCESS = "COMMON_CHATROOM_SUCCESS";
export const COMMON_CHATROOM_FAIL = "COMMON_CHATROOM_FAIL";

export const LIST_USER_CHATROOMS_REQUEST = "LIST_USER_CHATROOMS_REQUEST";
export const LIST_USER_CHATROOMS_SUCCESS = "LIST_USER_CHATROOMS_SUCCESS";
export const LIST_USER_CHATROOMS_FAIL = "LIST_USER_CHATROOMS_FAIL";
export const LIST_USER_CHATROOMS_RESET = "LIST_USER_CHATROOMS_RESET";

export const CREATE_ATTACHMENT = "CREATE_ATTACHMENT";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CREATE_MESSAGE_RESET = "CREATE_MESSAGE_RESET";

export const UPDATE_CHATROOM = "UPDATE_CHATROOM";
