export const FOLLOWINGS_BY_AUTH_USERID = "FOLLOWINGS_BY_AUTH_USERID";
export const FOLLOWERS_BY_AUTH_USERID = "FOLLOWERS_BY_AUTH_USERID";
export const ON_CREATE_FOLLOWING = "ON_CREATE_FOLLOWING";
export const ON_CREATE_FOLLOWER = "ON_CREATE_FOLLOWER";
export const ON_DELETE_FOLLOWING = "ON_DELETE_FOLLOWING";
export const ON_DELETE_FOLLOWER = "ON_DELETE_FOLLOWER";

export const CHECK_FOLLOWING = "CHECK_FOLLOWING";
export const CHECK_FOLLOWER = "CHECK_FOLLOWER";
export const CREATE_FOLLOWING = "CREATE_FOLLOWING";
export const CREATE_FOLLOWER = "CREATE_FOLLOWER";
export const DELETE_FOLLOWING = "DELETE_FOLLOWING";
export const DELETE_FOLLOWER = "DELETE_FOLLOWER";

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
