export const ON_CREATE_COMMENT_POST = "ON_CREATE_COMMENT_POST";
export const ON_CREATE_COMMENT_FEED = "ON_CREATE_COMMENT_FEED";
export const GET_POST = "GET_POST";

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const COMMENTS_BY_TWEETID_REQUEST = "COMMENTS_BY_TWEETID_REQUEST";
export const COMMENTS_BY_TWEETID_SUCCESS = "COMMENTS_BY_TWEETID_SUCCESS";
export const COMMENTS_BY_TWEETID_FAIL = "COMMENTS_BY_TWEETID_FAIL";
export const COMMENTS_BY_TWEETID_RESET = "COMMENTS_BY_TWEETID_RESET";

export const TWEETS_BY_USERID_REQUEST = "TWEETS_BY_USERID_REQUEST";
export const TWEETS_BY_USERID_SUCCESS = "TWEETS_BY_USERID_SUCCESS";
export const TWEETS_BY_USERID_FAIL = "TWEETS_BY_USERID_FAIL";
export const TWEETS_BY_USERID_RESET = "TWEETS_BY_USERID_RESET";

export const LIKES_BY_USERID_REQUEST = "LIKES_BY_USERID_REQUEST";
export const LIKES_BY_USERID_SUCCESS = "LIKES_BY_USERID_SUCCESS";
export const LIKES_BY_USERID_FAIL = "LIKES_BY_USERID_FAIL";
export const LIKES_BY_USERID_RESET = "LIKES_BY_USERID_RESET";

export const COMMENTS_BY_USERID_REQUEST = "COMMENTS_BY_USERID_REQUEST";
export const COMMENTS_BY_USERID_SUCCESS = "COMMENTS_BY_USERID_SUCCESS";
export const COMMENTS_BY_USERID_FAIL = "COMMENTS_BY_USERID_FAIL";
export const COMMENTS_BY_USERID_RESET = "COMMENTS_BY_USERID_RESET";

export const MEDIA_BY_USERID_REQUEST = "MEDIA_BY_USERID_REQUEST";
export const MEDIA_BY_USERID_SUCCESS = "MEDIA_BY_USERID_SUCCESS";
export const MEDIA_BY_USERID_FAIL = "MEDIA_BY_USERID_FAIL";
export const MEDIA_BY_USERID_RESET = "MEDIA_BY_USERID_RESET";

export const CREATE_COMMENT = "CREATE_COMMENT ";
export const CREATE_COMMENT_POST = "CREATE_COMMENT_POST";
export const CREATE_TWEET = "CREATE_TWEET";

export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";

export const LIST_FOLLOWINGS_FOR_TIMELINE_REQUEST =
  "LIST_FOLLOWINGS_FOR_TIMELINE_REQUEST";
export const LIST_FOLLOWINGS_FOR_TIMELINE_SUCCESS =
  "LIST_FOLLOWINGS_FOR_TIMELINE_SUCCESS";
export const LIST_FOLLOWINGS_FOR_TIMELINE_FAIL =
  "LIST_FOLLOWINGS_FOR_TIMELINE_FAIL";
